### ISSUE TITLE
Support String interpolation

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3286]
Users currently have to do concatenation like so:

```
"I am "
|> ++ user.name
|> ++ " and I am "
|> ++ (toString user.age)
|> ++ " years old"
```

**Solution**: Instead, we'd like to support string interpolation

```
"I am ${user.name} and I am ${user.age} years old"
```

**Runtime Implementation**

I believe we can implement it with these types:

```
type stringSegment =
  | Text of string
  | InterpolatedExpr of expr

type Expr =
  | EString of stringSegment list
  | ...

type Pattern = ... // no change
type Dval = ... // no change
```

**Editor Interaction**

Unsure what this would look like, but I imagine it would either:

- use a very similar ssyntax to JS (`"Interpolate this expr: ${1 + 2}"`, I don't see any reason to require backticks as we don't have the same legacy issues as JS). This has the advantage that it's very recognizable for JS devs
- use a less onerous syntax: `"Interpolate this expr: {1 + 2}"`

I imagine we'd only support simple expressions: values, simple function calls or infix ops, and `value.field`.

**Task list**:
- [ ] Design editor interaction model
- [ ] add frontend support for interpolation (this can be behind a flag and thrown away until we get the interactions right)
- [ ] add backend support for interpolation in the interpreter and SQL compiler. Add types to frontend (can be done separately from the frontend support - it's fine if it's not possible to actually add interpolation in the editor)

**Comment by jcmrva** [comment]
I really like F#/C# requiring only an indicator at the beginning: $"Adding {1} and {2} equals {1+2}."

**Comment by pbiggar** [comment]
Yeah. Though also I occasionally forget to add the `$` in front!

My preference is definitely the "less onerous" thing of just the braces, but also we don't have to make it purely syntacting - we can put more UI on it as it will only be edited via the Dark editor. So maybe the question is more "what keystroke do we use to allow string interpolation" and "how do we display string interpolation".

**Comment by pbiggar** [comment]
Not applicable in darklang-next (this is really about the frontend)
