### ISSUE TITLE
[roadmap] Fluid editor

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3292]
- [x] #3287
- [ ] line wrapping
- [ ] support unicode in variable/function names
- [ ] when var names are automatically created, highlight
- [ ] convert non-fluid stuff to fluid
  - [ ] types
  - [ ] datastores
  - [ ] function definitions
  - [ ] handlers
- [x] #3838
- [x] #3844

**Comment by pbiggar** [comment]
Closing
