### ISSUE TITLE
v2 program storage

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3298]
What behind-the-scenes upgrades are needed to support Dark v2.

- [ ] Store handlers with transitive list of toplevels to also load
- [ ] move cached storage to a fast cache (like redis)
- [ ] switch to using SetExpr where possible
- [ ] switch to "real" operational transforms

**Comment by StachuDotNet** [comment]
folding into #5246
