### ISSUE TITLE
[roadmap] package manager

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3439]
- [ ] Style guide
- [ ] User module
- [ ] ~package manager names are ugly in the UI~
- [ ] support transitive function upload
- [ ] design contribution workflow
- [ ] design package creation workflow
- [ ] allow imports of packages
- [ ] design search for packages
- [ ] allow importing or applying handler templates

**Comment by pbiggar** [comment]
We need support for this stuff, but enough has changed that this issue isn't useful.
