### ISSUE TITLE
Support for user-defined records

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3447]
- [x] convert built-in cookie type into a record
- [x] create "syntax" to update record fields
- [x] non-existent fields should create DErrors, not nulls
- [x] re-enable record creation
- [x] include package/stdlib module names in types
- [ ] allow piping to `.fieldname` like in Elm

**Comment by pbiggar** [comment]
Mostly done, remaining work not tracked here.
