### ISSUE TITLE
Support for user-defined enums

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3448]
- [x] Allow creating user defined enums
- [ ] Add Result and Option as types to the stdlib, convert existing DOption and DResult
- [x] how should enums be converted to json
- [x] how should enums be stored in the DB
- [x] add fully-qualified names to enums
- [ ] allow piping to a constructor name
- [ ] allow if-based destructuring/matching

**Comment by pbiggar** [comment]
Mostlt done. Remaining work not being tracked here.
