### ISSUE TITLE
Switch everyone over to new BwdServer

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3690]
Making a plan for how to switch everyone over.

## Issues that MUST be solved first

- [x] httpclient issue (#3680)
- [x] sqlcompiler issue (#3699)
- [x] #3710

## Issues that SHOULD be solved first

- [x] ~possible unicode bug (#3649) - (not a big deal)~
- [x] ~possible jwt bug (#3662) - (doing it later)~
- [x] hsts (#3677)
- [ ] compression (#3664)

## Issues that give us confidence that it will be fine

- [x] [FSHARPONLY vs OCAMLONLY](https://github.com/darklang/dark/projects/1#card-79560998)
- [x] performance (#3624) (probably ok here)
- [x] libstaticassets security (#3683)
- [ ] code coverage (#3688)
- [ ] fuzzing (#3556)

## How to actually go through the migration

- [x] make list of people with more than 100 requests to BwdServer per week
- [x] draft email
- [x] notify them by email
- [x] wait a few days, see if any volunteers come up
- [x] starting from the smallest, switch them over (possibly a handler at a time for larger users)
- [x] watch for changes in status code, latency, response size, rollbars
- [x] wait a few days for reports, etc
- [x] switch the DNS

**Comment by pbiggar** [comment]
Currently, one canvas breaks on the new thing due to invalid json. One customer has asked to go last.

So we're good to switch over all canvases except those two. That can be done on the current load balancer, but can't be done after we switch the DNS (we're done at that point).

I'm going to start switching the custom domains over (some - mostly ours - have been switched already).

**Comment by pbiggar** [comment]
Done
