### ISSUE TITLE
Add tuple `match` pattern

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4427]
(I thought we had an issue around this, but I can't find it.)

![image](https://user-images.githubusercontent.com/906686/186996974-af06b252-6171-4354-9d31-979271720211.png)

TODOs:
- [x] basic functionality (in #4425)
  - the tuple match pattern _type_ is defined
  - the interpreter respects the new pattern, and basic tests pass
  - Fluid has been updated to add new new tuple pattern to a `match` (though only tuples of size 2, currently), and have its sub-patterns filled
- [x] once #4404 is merged, update the Interpreter to handle the new Tuple match pattern in the backend
- [x] (backend) more testing
- [x] (client) hide the new tuple pattern from users, or hide behind feature flag
- [x] duplicate bindings in the same Pattern should result in the 'right-most' one winning
  e.g. `match (1,2,3) with (a, 2, a) -> a` should return `3`
- [x] (Fluid) handle `,` inserts in the tuple match pattern (draft PR #4431)
- [x] lots of (Fluid) testing
- [x] include a tuple pattern in the pattern autocomplete (#4465)
- [x] reconstruction
- [ ] relevant TUPLETODOs
---

Relates to #3402. Needed for #4265.

**Comment by StachuDotNet** [comment]
Bug found:

```
match 1
  (|1, 2) -> "test"
```

Hitting 'a' keystroke here should do nothing, but it's currently replacing the 1 pattern.
(replacing the `PInteger 3` pattern with a `PString "a"` pattern)

**Comment by StachuDotNet** [comment]
This is good - there are some minor todos around reconstruction, but they're already marked as TUPLETODOs and noted in #4265 as a blocker for fully enabling tuples for users
