### ISSUE TITLE
Component: Internal things to improve

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#5246]
This Issue exists to collect many items, not currently in progress, that don't quite effect users, but we still want to address at some point.

(If an issue is urgent, or important enough, then it should have its own issue.)

- [ ] Everything marked TODO in the codebase
- [ ] Everything marked CLEANUP in the codebase (was #3938)
- [ ] Somehow report on types allow<>'d to be serialize that are unused (see #4589)
- [ ] Prevent Timeout exceptions from being rollbar'd (see #4092)
- [ ] Decide between `init`, `lazy`, and passing values for startup values and singletons (see #3944)
- [ ] Lock dotnet tool versions in Dockerfile (see #3896)
- [ ] Warm up BwdServer when it starts (see #3782)
- [ ] Run F# backend against coverage tool (see #3688)
- [ ] Document/Fix F# Debugging (see #3634)
- [ ] Consider banning `string` function (see #3567)
- [ ] improve F# build performance (see #2952)
- [ ] Include reference to user in rollbars created by queueworker (see #3905)

Once we start on any of these,
- extract the bullet into its own issue, copying any relevant notes
- , and delete the bullet here
