### ISSUE TITLE
Component: Cloud Runtime

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#5261]
The "Cloud" runtime is a collection of cloud-hosted services that Dark supports, including Http Handlers, Crons, Queues, cloud-run Scripts (previously known as REPLs). Your code is stored on the cloud, and we take care of everything else.

- [ ] baseline -- bring back the "Dark Cloud" in dark-next
- [ ] general - restricting usage of these constructs only to Cloud-hosted code
- DBs
  - [ ] bring back 
- Http Handlers (`BwdServer`)
  - [ ] bring back Http Handlers hosted by Dark
  - [ ] back-fill a lot of tests (see #4763)
  - [ ] how do custom domains work in this new world?
    - [ ] see 3327
  - [ ] reimplement LibMiddleware (see #4151)
- Crons
  - [ ] bring Crons back, in the most minimal capacity, in dark-next
  - [ ] allow pausing crons (see old #2646)
- Queues
  - [ ] Bring back Queues, in some minimal capacity
- [ ] general: Outbound IP address (see old #4675)
- [ ] general: send user alerts and notifications (see #3991)
- [ ] disable crons and workers which do nothing (see #3958)
