### ISSUE TITLE
Component: CRONs

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#5396]
This Issue exists to collect many items that relate to "Crons" in Darklang - code that is scheduled to run on some pre-set interval or time.

In Darklang-classic, Crons only existed in our Cloud runtime (since that was the only runtime), but going forward we should have them supported for the Local/CLI runtime as well. (likely a wrapper of OS-level functionality)

- [ ] bring them back locally / CLI
- [ ] bring them back in the cloud
- [ ] disable Crons which do nothing (see #3958)
- [ ] allow pausing crons (see old #2646)
- [ ] we should have more control over cron timing (see discussion in #3842)
- [ ] prevent deploy from killing old CronChecker deployment until the new one is in place #3671
