### ISSUE TITLE
Component: HTTP Handlers

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#5397]
This Issue exists to collect many items that relate to "Crons" in Darklang - code that is scheduled to run on some pre-set interval or time.

In Darklang-classic, HTTP Handlers only existed in our Cloud runtime (since that was the only runtime), but going forward we should have them supported for the Local/CLI runtime as well.

- [ ] bring them back locally, in some minimal capacity
- [ ] how do custom domains work in this new world? (see #3327)
- [ ] reimplement LibMiddleware (see #4151 and #3892. also #3407)
- [ ] revisit how we handle responses, esp errors (#4572)
- [ ] warm up BwdServer when it starts (see #3782)
- [ ] look at `opts.Limits.MaxConcurrentconnections` (likely applies to `bwdserver`)
